### ISSUE TITLE
the status is connected, but can't access google, twitter, youtue...

### ISSUE THREAD

**Issue by EricDong** [wuwei-thu/vpn#2]
with lipan's solution, I cann't connect the vpn.
with your solution, I can connect the vpn, but can't browse webistes like google, twitter, youtube......
I don't know why.

**Comment by wuwei-thu** [comment]
since it can be connected, the vpn service is ok. The service use L2TP protocol.
Make sure you chose the selection “send all traffic over VPN connection ”

[image0.png]
发自我的 iPhone

在 2022年12月31日，17:02，Eric Dong ***@***.***> 写道：

﻿

with lipan's solution, I cann't connect the vpn.
with your solution, I can connect the vpn, but can't browse webistes like google, twitter, youtube......
I don't know why.

**Comment by wuwei-thu** [comment]
> 

Does it work now?

**Comment by EricDong** [comment]
Thanks for your alert.
Now it's OK.
